### PR TITLE
Update README.md [skip ci]

### PR DESCRIPTION
**Pull request by mehalyna**
Add SonarCloud badges

## Summary of change

Added  some new badges from [sonarCloud](https://sonarcloud.io/dashboard?id=ita-social-projects-events-express)

## CHECK LIST
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

### CODE REVIEW

**Comment by sand0** [comment]
I've dropped that project on sonarcloud, so we need to have a new one working to finish this update

**Review by Anastasiagumenuk9 — APPROVED** [review]

**Pull request merged**
