### PR TITLE
Added event filtering for registered & unregistered users

### LINKED ISSUE #714: [Landing Page][Block3] As a Registered User I want to see all upcoming events, so that I can choose the most suitable for me
**Pre-requisites**
Criteria to be fulfilled before realize:

**Description**

Once a Registered User press the button "Explore more events", the system redirects a Registered User to the "filter of events" window. (Systems shows for Registered User private and public events)

**Acceptance criteria**

|Given| A Registered User scrolled the landing page to the Block 3
|When| Registered User press the button "Explore more events"
|Then| The system redirects a Registered User to the "filter of events" window
|And| The Systems shows for Registered User private and public events

**Additional context**
Block3 _Landing_page

**Epic link** E.g.: Epic #100 Epic

**Labels to be added** "User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### LINKED ISSUE #715: [Landing Page][Block3] As a Unregistered User I want to see all upcoming events, so that I can choose the most suitable for me
**Pre-requisites**
Criteria to be fulfilled before realize:

**Description**
Once a Unregistered User press the button "Explore more events", the system redirects a Unregistered User to the "filter of events" window. (Systems shows for Unregistered User only public events)

**Acceptance criteria**
|Given| A Unregistered User scrolled the landing page to the Block 3
|When| Unregistered User press the button "Explore more events"
|Then| The system redirects an Unregistered User to the "filter of events" window
|And| The Systems shows for Unregistered User only public events

**Additional context**

Block3 _Landing_page

**Epic link** E.g.: Epic #100 Epic

**Labels to be added** "User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### PR DESCRIPTION
**Pull request by Junomy**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

User can see private & public events, even though it is not registered.

## Summary of change

Unregistered users can see only public events.
Registered users can see private & public events.

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Comment by sand0** [comment]
What exactly requirement drives these changes? 
As far as I remember, 'private' events are for restricting joining (so users can join after the event owner has approved that participation), not visibility restricting.

@mehalyna , FYI

**Comment by sand0** [comment]
In case we want to show events for unregistered users, I guess we should replace the `join` button with something like `sign in to join`

**Comment by mehalyna** [comment]
> What exactly requirement drives these changes?
> As far as I remember, 'private' events are for restricting joining (so users can join after the event owner has approved that participation), not visibility restricting.
> 
> @mehalyna , FYI

Yes, this is my problem. I forgot about the restrictions imposed by private status

**Comment by mehalyna** [comment]
> In case we want to show events for unregistered users, I guess we should replace the `join` button with something like `sign in to join`

do you really see the point in this?

**Review by iuriikhrystiuk — APPROVED** [review]

**Comment by sand0** [comment]
Need to clarify requirements and use cases for feature

**Pull request closed without merging**
